src/data/hotels.js
=> FIX-MT-F2-02

src/data/cities.js
=> FIX-MT-F1-01

src/components/Home2/Carrousel/Carrousel.css, src/components/Home2/Carrousel/Carrousel.jsx, src/components/Home2/Carrousel/Slideshow.jsx, src/components/Home2/Carrousel/Thumbnail.jsx, src/components/Home2/Home2.jsx, src/layouts/Footer/Footer.css, src/layouts/Footer/Footer.jsx, src/layouts/Footer/FooterNav/FooterNav.jsx, src/layouts/Footer/FooterToUp/FooterToUp.jsx
=> [MT-F2-04] Home2

src/App.js, src/components/404/NotFound.css, src/components/404/NotFound.jsx
Re-added files because a version deleted it.
=> FIX MT-F2-06

src/components/home1/Navbar/NavBar.css, src/layouts/Header/Header.css
=> FIX MT F1 03

src/components/404/NotFound.css, src/components/404/NotFound.jsx
=> [FIX MT F2-06] #Update

src/components/LoginForm/LoginForm.jsx
=> [FIX-MT-F2-08]

src/App.js, src/layouts/Home.css, src/layouts/Home.jsx, src/pages/Hoome.jsx
=> [MT-F1-05] Home Page

src/App.js, src/components/SignUpForm/SignUpForm.css, src/components/SignUpForm/SignUpForm.jsx, src/pages/signUp/SignUp.css, src/pages/signUp/SignUp.jsx
=> [MT-F1-07] Register Page

src/components/LoginForm/LoginForm.jsx
-Fixed Google Button
-Fixed Object as LS.
-Fixed Layout
Evidence:
=> Fix mt f2 08

src/App.js, src/layouts/Main.css, src/layouts/Main.jsx, src/pages/Home.jsx
=> Fix mt f1 05

src/components/home1/Home1.jsx, src/layouts/Main.jsx, src/pages/Home.jsx
=> FIX-MT-F1-05

src/App.js, src/components/404/NotFound.jsx
=> FIX-MT-F2-06

src/App.js
=> Fix mt f1 07

src/components/Home2/Carrousel/Carrousel.css, src/layouts/Footer/Footer.jsx, src/layouts/Footer/FooterToUp/FooterToUp.jsx
Footer ClassName fixed
Home2 height fixed.
=> [FIX-MT-F2-04] Footer / Home2 Fix

src/components/home1/Home1.jsx, src/components/home1/Navbar/NavBar.css, src/components/home1/Navbar/NavBar.jsx, src/components/home1/Navbar/NavBar2.jsx, src/layouts/Header/Header.jsx
=> [FIX-MT-F1-03] Home1

src/App.js, src/components/LoginForm/LoginForm.css, src/components/LoginForm/LoginForm.jsx
-Added button of Google
-Added button of Register Page
-Changed URL
=> [FIX-MT-F2-08] Update

src/components/SignUpForm/SignUpForm.jsx, src/components/home1/Navbar/NavBar.jsx, src/pages/signUp/SignUp.jsx
Se cambio rutas invertidas
de signUp y signIn
=> [MT-F1-07] Register Page 

src/App.js, src/components/NewHotel/NewHotel.css, src/components/NewHotel/NewHotel.jsx
=> [MT-F2-14]  NewHotel+

src/data/hotels.js
=> [FIX-MT-F2-02]

src/data/cities.js
Se modifico los id de cities.js
=> [MT-F1-01] Datos #1

src/App.js, src/components/NewCity/NewCity.css, src/components/NewCity/NewCity.jsx
=> [MT-F1-13] City+

src/App.js, src/components/HotelsPage/HotelPrinter.jsx, src/components/HotelsPage/Hotels.css, src/components/HotelsPage/Hotels.jsx
=> [MT-F2-10]

src/components/NewHotel/NewHotel.css, src/components/NewHotel/NewHotel.jsx
=> [FIX-MT-F2-14]

src/components/HotelsPage/Hotels.jsx
- Simple filter by alphabetic fixed
=> [FIX-MT-F2-10]

public/index.html, src/index.css, src/index.js
Icon added, smooth scroll added, scroll-Y modified, custom font added.
=> General Update 

src/App.js, src/components/DetailsHotel/DetailsHotels.css, src/components/DetailsHotel/DetailsHotels.jsx, src/components/DetailsHotel/Show.jsx, src/components/HotelsPage/HotelPrinter.jsx, src/data/show.js
=> [MT-F2-12] Details 

src/App.js, src/components/Cities/Cities.css, src/components/Cities/Cities.jsx, src/components/Cities/CitiesPrinter.jsx, src/components/DetailsCities/DitailsCities.css, src/components/DetailsCities/DitailsCities.jsx, src/components/checkbox/Checkbox.jsx, src/data/citiesActivity.js, src/layouts/Main.css
=> Mt f1 09+mt f1 11

src/api/url.js, src/components/NewHotel/NewHotel.jsx
=> [MT-02-23]

src/components/DetailsHotel/DetailsHotels.css, src/components/DetailsHotel/DetailsHotels.jsx, src/components/DetailsHotel/Show.jsx, src/components/HotelsPage/Hotels.jsx, src/index.js
=> FIX-SPRINT-2-MT-26-02

src/App.js, src/components/MyShows/EditShowCard.css, src/components/MyShows/EditShowCard.jsx, src/components/MyShows/ShowCards.jsx, src/components/MyShows/Shows.css, src/pages/myShows/myShows.css, src/pages/myShows/myShows.jsx, src/redux/actions/myShowAction.js, src/redux/reducers/myShowReducer.js, src/redux/reducers/rootReducer.js
=> [MT-02-44]

package-lock.json, package.json, src/components/LoginForm/LoginForm.jsx, src/index.js, src/redux/actions/loginForm.js, src/redux/reducers/loginReducer.js, src/redux/reducers/rootReducer.js
=> [MT-02-46]

src/App.js, src/components/Header/Header.jsx, src/components/LoginForm/LoginForm.jsx, src/components/home1/Navbar/NavBar.jsx
**Evidence:**
https://user-images.githubusercontent.com/108221247/204149920-10587e9e-6363-4ee6-9697-c24348567f37.mp4
=> [MT-02-48]

src/App.js, src/components/Header/Header.jsx, src/components/Profile/ViewProfile1.jsx, src/components/Profile/ViewProfile2.jsx, src/components/Profile/components/EditProfile.jsx, src/components/Profile/components/SeeProfile.jsx, src/components/Profile/styles/ViewProfile1.css, src/components/Profile/styles/ViewProfile2.css, src/components/home1/Navbar/NavBar.css, src/components/home1/Navbar/NavBar.jsx
=> [MT-02-50]

src/components/Profile/components/EditProfile.jsx, src/components/Profile/styles/ViewProfile1.css, src/components/Profile/styles/ViewProfile2.css
=> [FIX-MT-02-50]

src/App.js, src/components/Header/Header.jsx, src/components/NewShow/NewShow.css, src/components/NewShow/NewShow.jsx, src/components/home1/Navbar/NavBar.css, src/components/home1/Navbar/NavBar2.jsx
=> [MT-02-52]

src/App.js, src/components/Header/Header.jsx, src/components/MyShows/ShowCards.jsx, src/components/MyShows/Shows.css, src/components/NewShow/NewShow.css, src/components/NewShow/NewShow.jsx, src/components/home1/Navbar/NavBar2.jsx, src/pages/myShows/myShows.css, src/pages/myShows/myShows.jsx
**Evidence:**
Usuario sin shows:
Usuario con shows (traidos por token):
=> [FIX-MT-02-52]

src/pages/myHotels/myHotels.jsx
**Evidence:**
User without Hotels Created:
User with Hotels created:
=> [MT-02-54]

src/components/MyHotels/EditCard.jsx, src/components/MyShows/EditShowCard.jsx, src/redux/actions/myHotelAction.js, src/redux/actions/myShowAction.js
Fix front token validation to backend
=> [FIX-sprint 4]

src/components/MyHotels/Cards.jsx, src/components/MyShows/EditShowCard.jsx, src/components/MyShows/ShowCards.jsx, src/components/NewHotel/NewHotel.jsx, src/components/NewShow/NewShow.jsx, src/pages/myHotels/myHotels.jsx, src/pages/myShows/myShows.jsx
=> [FIX-SPRINT-4]

src/components/MyCities/EditCard.jsx, src/components/MyItinerary/EditItineraryCard.jsx, src/pages/NewItineraries/NewItineraries.jsx, src/redux/actions/myCityAction.js, src/redux/actions/myItineraryAction.js
=> Fix sprint 4 front

src/App.css, src/App.js, src/components/DetailsHotel/Comments.css, src/components/DetailsHotel/Comments.jsx, src/components/DetailsHotel/DetailsHotels.css, src/components/DetailsHotel/NewComments.css, src/components/DetailsHotel/NewComments.jsx, src/components/DetailsHotel/Show.jsx, src/components/Header/Header.jsx, src/components/LoginForm/LoginForm.jsx, src/index.css, src/redux/actions/commentsAction.dat, src/redux/actions/myCommentsAction.js, src/redux/actions/tokenAction.js, src/redux/reducers/commentReducer.dat, src/redux/reducers/myCommentsReducer.js, src/redux/reducers/rootReducer.js, src/redux/reducers/tokenReducer.js
=> [MT-02-58]

src/App.css, src/components/DetailsHotel/Comments.css, src/components/DetailsHotel/Comments.jsx, src/components/DetailsHotel/DetailsHotels.css, src/components/DetailsHotel/NewComments.css, src/components/DetailsHotel/NewComments.jsx, src/components/DetailsHotel/Show.jsx, src/components/LoginForm/LoginForm.jsx, src/index.css, src/redux/actions/commentsAction.dat, src/redux/actions/tokenAction.js, src/redux/reducers/commentReducer.dat, src/redux/reducers/rootReducer.js, src/redux/reducers/tokenReducer.js
Evidence:
https://user-images.githubusercontent.com/108221247/205222023-6f7deb7c-bde7-4464-9c4f-f509890acc0d.mp4
=> [MT-02-57]

src/api/url.js, src/components/DetailsHotel/NewComments.jsx, src/pages/Cities/Cities.jsx, src/pages/DetailsCities/Comments.css, src/pages/DetailsCities/Comments.jsx, src/pages/DetailsCities/DitailsCities.css, src/pages/DetailsCities/DitailsCities.jsx, src/redux/actions/cityAction.js, src/redux/actions/myCommentsAction.js, src/redux/reducers/commentReducer.js, src/redux/reducers/rootReducer.js
=> general fixes + mt-02-60
